print("###############################")
print("#                             #")
print("#   Mohammad Zaki Firmansah   #")
print("#        221081711006         #")
print("#                             #")
print("###############################")